name: chat_app_flutter_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.0
  flutter:
    sdk: flutter
  get: 4.6.1
  google_sign_in: ^5.2.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
