// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFEt-XBEqb24bH9O69ppm3p63OdNXbXg',
    appId: '1:843773862758:web:48a296f302bc31f45a5ea7',
    messagingSenderId: '843773862758',
    projectId: 'chatapps-firman',
    authDomain: 'chatapps-firman.firebaseapp.com',
    storageBucket: 'chatapps-firman.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NcWwXTP0tiXFGEl5X9qOKkfcunT65h0',
    appId: '1:843773862758:android:28f1ead4c75b30c25a5ea7',
    messagingSenderId: '843773862758',
    projectId: 'chatapps-firman',
    storageBucket: 'chatapps-firman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJmJ0ENOxKapgGNTI2VC4CFCoZQKoZU4',
    appId: '1:843773862758:ios:b3c783be9c2ac0d75a5ea7',
    messagingSenderId: '843773862758',
    projectId: 'chatapps-firman',
    storageBucket: 'chatapps-firman.appspot.com',
    androidClientId: '843773862758-326l2mrkvbdf85vj9t9numvf16n1m957.apps.googleusercontent.com',
    iosClientId: '843773862758-9r3dv351a7q7ugutv566p4ttv1pd89ae.apps.googleusercontent.com',
    iosBundleId: 'firmandev.com',
  );
}
